apiVersion: v2
name: payment-service
description: Mock payment gateway service for Octo E-Shop
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - octo-eshop
  - microservice
  - payment
  - gateway
maintainers:
  - name: Platform Team
    email: platform@octo-eshop.example.com
