apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-__ENV__
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: __VAULT_URL__
      tenantId: __TENANT_ID__
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets
